### ISSUE TITLE
Question about python library

### ISSUE THREAD

**Issue by eternitygod** [Blimba/PyWC3#2]
### When trying to import the request library, the tool could not be fully converted to lua language.

- Before build
```
from urllib.request import urlopen, Request

response = Request("https://www.python.org/")
```

- After build
```
local response = Request(("https://www.python.org/"))
```

- Error
```
war3map.lua:4639 : attempt to cal a nil value (global 'Request')
```

**Comment by Blimba** [comment]
external libraries are not supported in the translator. You may only import your own pure python libraries.
